name: pps 
channels:
  - conda-forge
dependencies:
  - foyer
  - freud
  - gsd
  - hoomd=3.7=*gpu*
  - matplotlib
  - mbuild
  - mdanalysis
  - numpy
  - pip
  - pymbar < 4.0
  - pytest
  - pytest-cov
  - python=3.9
  - rowan
  - signac=1.7.0
  - signac-flow=0.18.1
  - unyt
  - pip:
      - git+https://github.com/cmelab/cmeutils.git@master
      - git+https://github.com/chrisjonesbsu/hoomd-polymers.git@main
